name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Install Nix
        uses: cachix/install-nix-action@b97f05dcb019ddea06450a50ef6203d2fdc19fee # v31
      - name: Set up Cachix
        uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: fleet-nixos
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Run root flake checks and builds
        run: nix flake check # Note, check includes build of orbit.
      - name: Run development flake checks
        run: nix flake check ./dev
